# Site settings
title: Catherine Moresco
email: catherine.moresco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://catmores.co" # the base hostname & protocol for your site
twitter_username: catmoresco
github_username:  catherinemoresco

# Build settings
markdown: redcarpet

analytics :
  provider : google
  google : 
      tracking_id : 'UA-56925026-1'
  getclicky :
    site_id :